# general settings
baseurl         = "/"
languageCode    = "en-us"
themesDir       = "node_modules"
theme           = "hello-friend"
paginate        = 5
enableGitInfo   = true
enableRobotsTXT = true

# better resampling algorithm
[imaging]
  quality = 95
  resampleFilter = "Lanczos"

# markdown settings
[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
  footnote = true

[markup.goldmark.renderer]
  # needed for superscript
  unsafe = true

[markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  anchorLineNos = true
  # https://xyproto.github.io/splash/docs/all.html
  style = "vulcan"

# theme parameters
[params]
  contentTypeName = "posts"
  defaultTheme    = "dark"
  showMenuItems   = 2
  showReadingTime = true
  toc             = true
  rssFullText     = true

  # default open graph image
  images = ["img/opg.png"]

[languages]
  [languages.en]
      title       = "Nathan Vaughn"
      copyright = "Written by a human, for humans"

    [languages.en.params]
      keywords    = ["programming", "tech", "Nathan", "Vaughn", "blog"]
      description = "Adventures in programming and tech"
      subtitle    = "Adventures in programming and tech"
      lastModDisplay = "Last Modified:"

    # logo parameters
    [languages.en.params.logo]
      logoText     = "nathanv@blog"
      logoHomeLink = "/"

  # extra links
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "Homepage"
      name       = "Homepage"
      weight     = 10
      url        = "https://nathanv.me"

    [[languages.en.menu.main]]
      identifier = "links"
      name       = "Links"
      weight     = 20
      url        = "https://links.nathanv.me/"
